import type { Metadata } from "next";
import "./globals.css";
import {Background} from "@/components/background/background";


import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import {ClientThemeProvider} from "@/components/clientThemeProvider/clientThemeProvider";
import {LocationProvider} from "@/components/locationProvider/locationProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >

      <AppRouterCacheProvider>
          <LocationProvider>
          <ClientThemeProvider>
              <Background/>
        {children}
          </ClientThemeProvider>
          </LocationProvider>
      </AppRouterCacheProvider>
      </body>
    </html>
  );
}
